# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'AnimeCalendar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for AnimeCalendar

  # Reactive
  pod 'RxSwift'
  pod 'RxCocoa'

  # Youtube trailer player
  pod 'youtube-ios-player-helper'

  # Image downloading
  pod 'Nuke', '10.7.1'

end
